### ISSUE TITLE
Errors and Warnings in TYPO3 V10 in Backend, Fatal Error in Frontend

### ISSUE THREAD

**Issue by blondo** [xima-media/xm_formcycle#2]
We are currently upgrading from TYPO3 V8 to V10 (V10.4.6) and have installed the extension. In the backend there are errors and depracted warnings in the module Upgrade -> Scan Extension Files (screenshots 1 and 2) and in the frontend there is a fatal error (screenshot 3).
Please deal with the issue as soon as possible, as we are in the middle of the upgrade.

Thank you verry much

<img width="996" alt="Screenshot1" src="https://user-images.githubusercontent.com/7349181/91154404-c962e680-e6c1-11ea-88f2-4360c689e85c.png">
<img width="996" alt="Screenshot2" src="https://user-images.githubusercontent.com/7349181/91154407-ca941380-e6c1-11ea-9016-21efc805e2fb.png">
<img width="1167" alt="Screenshot3" src="https://user-images.githubusercontent.com/7349181/91155133-b43a8780-e6c2-11ea-820f-438cf05b61d3.png">

**Comment by ximamedia** [comment]
Hello @blondo,

we updated the extension to version 7.1.2 regarding the deprecation messages of the upgrade scan tool.
