### ISSUE TITLE
Jquery UI images are missing

### ISSUE THREAD

**Issue by woemar** [xima-media/xm_formcycle#37]
The images referenced in Resources/Public/Css/Frontend/jquery-ui.min.css are missing so that e.g. the datepicker will not have arrows to change the month when using Jquery UI.

Fix: add images to this extension.

**Comment by woemar** [comment]
Added https://github.com/xima-media/xm_formcycle/pull/38 to add the images

**Comment by maikschneider** [comment]
Perfect, thank you!
